% -------------------------------------------------------------------
%  Generated by MATLAB on 12-May-2019 12:16:45
%  MATLAB version: 9.1.0.441655 (R2016b)
% -------------------------------------------------------------------
saveVarsMat = load('sim3.mat');

A = ...
  [0 0 0 1 0 0;
   0 0 0 0 1 0;
   0 0 0 0 0 1;
   -3 0 0 -3 0 0;
   0 -3 0 0 -3 0;
   0 0 -2 0 0 -2];

B = ...
  [0 0 0;
   0 0 0;
   0 0 0;
   3 0 0;
   0 3 0;
   0 0 2];

C = [0 0 0 1 1 1];

D = [0 0 0];

I = ...
  [0.33333333333333331 0 0;
   0 0.33333333333333331 0;
   0 0 0.5];

M = 1;

R = 1;

S = ...
  [0 0;
   0 0;
   0 0;
   0 0;
   0 0;
   0 0];

T = 0.1;

Tg = [0; -9.81; 0];

U = ...
  [0 0;
   0 0;
   0 0];

ans = [0; 0; 0];

d = [1; 1; 1];

ddq = ...
  [0 0;
   0 0;
   0 0];

dq = ...
  [0 0;
   0 0;
   0 0];

f = 10;

g = -9.81;

h = 1;

k = [1; 1; 1];

q = ...
  [0 0;
   0 0;
   0 0];

sys = saveVarsMat.sys; % <1x1 ss> unsupported class

sysd = saveVarsMat.sysd; % <1x1 ss> unsupported class

t = [];

t_end = 10;

t_plot = saveVarsMat.t_plot; % <1x1001 double> too many elements

t_steps = saveVarsMat.t_steps; % <1x1001 double> too many elements

clear saveVarsMat;
